name: Deployment

on:
    pull_request:
        types: [closed]
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: ⚙️ Configure GitHub Actions
              uses: actions/checkout@v2
            - name: ⚙️ Heroky deploy
              uses: 🚀 akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'thingst'
                  heroku_email: 'rorem.94.developer@gmail.com'
